image: archlinux

cache:
  key: system-v1
  paths:
    # For some reason Gitlab CI only supports storing cache/artifacts in a path relative to the build directory
    - .pkg-cache

before_script:
  - pacman -Syu --noconfirm --noprogressbar --needed --cachedir .pkg-cache
           base-devel git gpgme protobuf pyalpm python-mysql-connector
           python-pygit2 python-srcinfo python-bleach python-markdown
           python-sqlalchemy python-alembic python-pytest python-werkzeug
           python-pytest-tap python-fastapi hypercorn nginx python-authlib
           python-itsdangerous python-httpx python-jinja python-pytest-cov
           python-requests python-aiofiles python-python-multipart
           python-pytest-asyncio python-coverage python-bcrypt postfix
           python-email-validator openssh
  - bash -c "echo '127.0.0.1' > /etc/hosts"
  - bash -c "echo '::1' >> /etc/hosts"
  - postfix start

test:
  script:
    - python setup.py install
    - sed -r "s;YOUR_AUR_ROOT;$(pwd);g" conf/config.dev > conf/config
    - AUR_CONFIG=conf/config make -C po all install
    - AUR_CONFIG=conf/config python -m aurweb.initdb
    - make -C test
    - coverage report --include='aurweb/*'
