image: archlinux

cache:
  key: system-v1
  paths:
    # For some reason Gitlab CI only supports storing cache/artifacts in a path relative to the build directory
    - .pkg-cache

before_script:
  - pacman -Syu --noconfirm --noprogressbar --needed --cachedir .pkg-cache
           base-devel git gpgme protobuf pyalpm python-mysql-connector
           python-pygit2 python-srcinfo python-bleach python-markdown
           python-sqlalchemy python-alembic python-pytest python-werkzeug
           python-pytest-tap python-fastapi hypercorn nginx python-authlib
           python-itsdangerous python-httpx

test:
  script:
    - make -C test
